filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: false
      templates:
        - condition:
            contains:
              docker.container.labels.logging.enabled: "true"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              close_inactive: 5m
              clean_inactive: 24h
              ignore_older: 12h
              scan_frequency: 10s

filebeat.registry.path: /usr/share/filebeat/data/registry
filebeat.registry.file_permissions: 0600

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.logstash:
  hosts: ["logstash:5044"]
  bulk_max_size: 256
  backoff.init: 1s
  backoff.max: 60s

logging.level: warning
logging.to_stderr: true